# Basic Data Structures- Lists, Dictionaries, Arrays

# Lists

## Instantiation

In [1]:
data <- list(1.7, "hello")
data

[[1]]
[1] 1.7

[[2]]
[1] "hello"

## Accessing the First Element

In [4]:
data[[1]]

[1] 1.7

## Updating an Element

In [5]:
data[[2]] = 3.5
data[[2]]

[1] 3.5

## Slicing a List
Get the first 3 elements.

In [6]:
data[1:3]

[[1]]
[1] 1.7

[[2]]
[1] 3.5

[[3]]
NULL

## Finding the Length of a List

In [7]:
length(data)

[1] 2

## Accessing Elements at the End of a List

In [11]:
last = data[length(data)]
last

[[1]]
[1] 3.5

## Traversing Through a List by the Values in the List
Useful if you don't need the index, and you're not changing anything.

In [14]:
for(item in data){
    print(item)
}

[1] 1.7
[1] 3.5


## Traversing a List by Index in the List
Useful if you want to change items in the list.

In [15]:
for(i in 1:length(data)) {
    print(data[[i]])
}

[1] 1.7
[1] 3.5


## Contains
Returns FALSE or TRUE

In [16]:
is.element('hello', data)

[1] FALSE

In [18]:
'1.7' %in% data

[1] TRUE

## Removing an Element from a List by Position
The first element

In [32]:
data[-1]
data

list()

[[1]]
[1] 3.5

## Remove a Single Element from a List by Value 

In [39]:
data <- list(1,2,3)
data[data != 2]

[[1]]
[1] 1

[[2]]
[1] 3

## Split String to List
Break a string into a list based on delimiter (usually default is a space)

In [42]:
data <- strsplit("my string is", " ")[[1]]
data

[1] "my"     "string" "is"

## Make String from List/Array of Strings 

In [43]:
paste(data, collapse=' ')

[1] "my string is"

#  MAP/DICTIONARY (LIST WITH NAMES ATTRIBUTE)
Most common approach is list with names attributes. In this case all keys must be the same types (usually strings)

## Instantitation

In [64]:
song = list(A = "do", B = "re", C = "mi")
song

$A
[1] "do"

$B
[1] "re"

$C
[1] "mi"

##  Finding the Size of Dictionary

In [46]:
length(song)

[1] 3

## Looking up by Key in the Dictionary 

In [47]:
song[['A']]

[1] "do"

## Updating/Setting a Value

In [49]:
song[['A']] <- "do"
song[['A']]

[1] "do"

## Get the List of Keys

In [50]:
names(song)

[1] "A" "B" "C"

## Get a List of Values 

In [51]:
song

$A
[1] "do"

$B
[1] "re"

$C
[1] "mi"

## Determining if a Key is Present 

In [53]:
'A' %in% names(song)

[1] TRUE

## Removal

In [65]:
song[[1]] = NULL
song[[1]]

[1] "re"

## Traversal Through Dictionary Iterating by Key 

In [66]:
for(key in names(song)) {
    print(song[[key]])
}

[1] "re"
[1] "mi"


# 2D ARRAYS (Collection of Single Data Type

## Instantiation

In [7]:
data <- array(c(1,2,3,4), dim=c(2,2))
data

[,1] [,2]
[1,] 1    3   
[2,] 2    4

## Checking the Data Type 

In [70]:
class(data)

[1] "matrix"

## Finding the Dimensions of an Array 

In [72]:
dim(data)

[1] 2 2

## Finding the number of Rows or Columns of an Array 

In [74]:
nrow(data)
ncol(data)

[1] 2

[1] 2

##  Accessing the First Value in the Array

In [75]:
data[1,1]

[1] 1

## Setting a Value 

In [80]:
data[1,1] <- 2
data

[,1] [,2]
[1,] 2    3   
[2,] 2    4

## Copying an Array 

In [82]:
new_data <- data
new_data

[,1] [,2]
[1,] 2    3   
[2,] 2    4

## Creating a 2x2 Array of All Zeroes 

In [84]:
array(0,c(2,2))

[,1] [,2]
[1,] 0    0   
[2,] 0    0

## Creating a 3x3 Array of All Ones 

In [85]:
array(1, c(3,3))

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

## Slicing an Array
In this case, getting the first column

In [86]:
data[1:2,1]

[1] 2 2

In [90]:
data[, 1]

[1] 2 2

## Copying One Array into a Part of an Array
In this case, set the first column to all zeroes.

In [5]:
data[1:2,1] <- array(0,c(1,2))
data

[,1] [,2]
[1,] 0    3   
[2,] 0    4

## Transpose
Flipping rows and columns

In [12]:
#Before
square <- array(c(1,2,3,4,5,6,7,8,9), dim = c(3,3))
square

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [13]:
#After
t(square)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

## Combining 2 Arrays Vertically 

In [97]:
rbind(c(1,2,3), c(4,5,6))

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

## Reshaping a 1D Array to 2D

In [98]:
array(1:6, c(2,3))
# Shapes arrays columns first

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

## Reshape a 2D Array to 1D 

In [14]:
as.vector(data)
# by columns

[1] 1 2 3 4