# Language features: basic data structures - lists, dictionaries, arrays

# Lists (called Cell Arrays)
## Instantiation

In [10]:
data = {1.7, "hello"}

data =
{
  [1,1] =  1.7000
  [1,2] = hello
}



## Accessing the First Element 

In [2]:
data{1}

ans = 1.7


## Updating an Element 

In [14]:
data{1} = "hi"

data =
{
  [1,1] = hi
  [1,2] = hello
}



## Slicing a List (get the first 2 elements) 

In [15]:
data{1:2}

ans = hi
ans = hello


## Finding the Length of the List 

In [16]:
length(data)

ans =  2


## Accessing Elements at the End of a List 

In [17]:
last = data{length(data)}

last = hello


## Contains
Returns 1 or 0

In [22]:
test = "hi";
ismember(test, data)

ans = 1


## Removing an Element from a List by Position
The first element

In [24]:
data{1} = []

data =
{
  [1,1] = [](0x0)
  [1,2] = hello
}



# Map
All keys must be the same type (number or character strings)

## Instantiation 

In [28]:
keySet = {'Jan', 'Feb', 'March', 'April'};
valueSet = {327.2, 368.2, 197.7, 178.4};
mapObj = containers.Map(keySet,valueSet)

mapObj =

  containers.Map object with properties:

    Count     : 4
    KeyType   : char
    ValueType : double




## Finding the Size of the Map 

In [29]:
length(mapObj)

ans =  4


## Looking up by Key in the Map 

In [30]:
mapObj('Jan')

ans =  327.20


## Updating/Setting a Value 

In [31]:
mapObj('May') = 394.4

mapObj =

  containers.Map object with properties:

    Count     : 5
    KeyType   : char
    ValueType : double




## Get the List of Keys 

In [32]:
keys(mapObj)

ans =
{
  [1,1] = April
  [1,2] = Feb
  [1,3] = Jan
  [1,4] = March
  [1,5] = May
}



## Get the List of Values 

In [33]:
values(mapObj)

ans =
{
  [1,1] =  178.40
  [1,2] =  368.20
  [1,3] =  327.20
  [1,4] =  197.70
  [1,5] =  394.40
}



## Determining if a Key is Present 

In [34]:
isKey(mapObj, 'Jan')

ans = 1


## Removal 

In [35]:
remove(mapObj, 'Jan')

ans =

  containers.Map object with properties:

    Count     : 4
    KeyType   : char
    ValueType : double




# 2D Arrays

## Instantiation

In [38]:
data = [1,2; 3,4; 5,6]

data =

   1   2
   3   4
   5   6



## Finding the Dimensions of the Array 

In [39]:
size(data)

ans =

   3   2



## Find the Number of Rows 

In [40]:
size(data, 1)

ans =  3


## Find the Number of Columns 

In [41]:
size(data, 2)

ans =  2


## Accessing the First Value in the Array 

In [42]:
data(1,1)

ans =  1


## Setting a Value 

In [43]:
data(1,1) = 0

data =

   0   2
   3   4
   5   6



## Creating a 2x2 Array of All Zeroes 

In [44]:
zeros(2,2)

ans =

   0   0
   0   0



## Creating a 3x3 Array of All Ones 

In [45]:
ones(3,3)

ans =

   1   1   1
   1   1   1
   1   1   1



## Slicing an Array
In this case, getting the first column.

In [48]:
data(1:3,1)

ans =

   0
   3
   5



In [50]:
data(:,1)

ans =

   0
   3
   5



## Transpose
Flip the rows and columns.

In [51]:
transpose(data)

ans =

   0   3   5
   2   4   6



## Combining 2 Arrays Vertically

In [52]:
row1 = [1 2 3];
row2 = [4 5 6];
A = [row1; row2]

A =

   1   2   3
   4   5   6



## Reshaping a 1D Array to a 2D Array 

In [53]:
reshape(1:6, 2, 3)

ans =

   1   3   5
   2   4   6



## Reshape a 2D Array to a 1D Array 

In [54]:
data(:)

ans =

   0
   3
   5
   2
   4
   6

