# Assignment 9: Primer for Basic Data Structures with Answers

For help with this assignment, you can use the following table:
[basic data structures](https://docs.google.com/document/d/1Q5VfbGyep-nC7oBmGEExpQpbGa5nwpDz4gaSIYqxY8w/edit?usp=sharing)
*Note the table will not be sufficient on its own for you to complete the assignment, however in the cases where it is not sufficient it can point you to the correct function or approach to answer the problem*

## Lists

Make a list with the spelled-out number strings ‘one’, ‘two’, ‘three’, ‘four’, and ‘five’ in that order and call it myList.

In [13]:
myList <- list("one", "two", "three", "four", "five")

Remove ‘three’ from the list using positional indexing

In [14]:
myList<-myList[-3]
myList

[[1]]
[1] "one"

[[2]]
[1] "two"

[[3]]
[1] "four"

[[4]]
[1] "five"

Check if ‘four’ is in the list

In [15]:
is.element("four", myList)

[1] TRUE

Append ‘six’ to the end of the list, then print the length of the list

In [17]:
myList <- c(myList, "six")
myList

[[1]]
[1] "one"

[[2]]
[1] "two"

[[3]]
[1] "four"

[[4]]
[1] "five"

[[5]]
[1] "six"

Print only the last two items in the list

In [19]:
myList[4:5]

[[1]]
[1] "five"

[[2]]
[1] "six"

Print the contents of the list, but also next to each item print the length of the string (e.g. ‘one’ is 3, ‘four’ is 4) using a for loop

In [32]:
for(word in myList) {
    cat(word, "is", nchar(word), "\n")
}

one is 3 
two is 3 
four is 4 
five is 4 
six is 3 


Create a list only of the lengths of the strings and show your result. You can use the loop before to fill the list

In [35]:
wordLength <- list()
for(word in myList) {
    wordLength <- c(wordLength, nchar(word))
}
wordLength

[[1]]
[1] 3

[[2]]
[1] 3

[[3]]
[1] 4

[[4]]
[1] 4

[[5]]
[1] 3

# Dictionaries

Make a dictionary with the keys english words as below, and the values be the translation. 
You can use this language example (German) or choose your own.
*note: you need to make sure all of these words are represented as strings, in quotes*
* apple - Apfel
* apples - Äpfel
* I - Ich
* and - und
* like - mag
* strawberries - Erdbeeren

In [56]:
dictionary <- list("apple" = "Apfel", 
                   "apples" = "Äpfel",
                   "I" = "Ich",
                  "and" = "und",
                  "like" = "mag",
                  "strawberries" = "erdbeeren")
dictionary

$apple
[1] "Apfel"

$apples
[1] "Äpfel"

$I
[1] "Ich"

$and
[1] "und"

$like
[1] "mag"

$strawberries
[1] "erdbeeren"

Use the dictionary to look up the translation for ‘apple’ and ‘like’

In [38]:
dictionary[["apple"]]
dictionary[["like"]]

[1] "Apfel"

[1] "mag"

Make a variable var with the string “I like apples and strawberries”

In [40]:
var <- "I like apples and strawberries"
var

[1] "I like apples and strawberries"

Now create a list from var with each word a separate item (this is a string split operation)

In [43]:
varList <- strsplit(var, " ")
varList

[[1]]
[1] "I"            "like"         "apples"       "and"          "strawberries"

Iterate through the list you’ve created and replace any word in your dictionary with the translation

In [57]:
newList <- c()
for(word in varList[[1]]) {
    for(key in names(dictionary)) {
        if(word == key) {
        word <- dictionary[[word]]
        }
    }
    newList <- c(newList, word)
}
newList

[1] "Ich"       "mag"       "Äpfel"     "und"       "erdbeeren"

Now take your new list and turn it into a string with spaces between the words

In [58]:
newString <- ""
for(word in newList) {
    newString <- paste(newString, word, collapse = " ")
}
newString

[1] " Ich mag Äpfel und erdbeeren"

# Arrays

Create an array of zeros of size 8 x 8 and print the data type of the array

In [62]:
data <- array(0, dim = c(8,8))
data
class(data)

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0    0    0    0    0    0    0    0   
[2,] 0    0    0    0    0    0    0    0   
[3,] 0    0    0    0    0    0    0    0   
[4,] 0    0    0    0    0    0    0    0   
[5,] 0    0    0    0    0    0    0    0   
[6,] 0    0    0    0    0    0    0    0   
[7,] 0    0    0    0    0    0    0    0   
[8,] 0    0    0    0    0    0    0    0

[1] "matrix"

Fill the array with the numbers 1 to 64 first by row, then by column you may want to use a for loop inside a for loop to do this

In [66]:
num <- 1
for(i in 1:8) {
    for(j in 1:8) {
        data[i, j] = num
        num <- num + 1
    }
}
data
num <- 1
for(i in 1:8) {
    for(j in 1:8) {
        data[j, i] = num
        num <- num + 1
    }
}
data

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  1    2    3    4    5    6    7    8  
[2,]  9   10   11   12   13   14   15   16  
[3,] 17   18   19   20   21   22   23   24  
[4,] 25   26   27   28   29   30   31   32  
[5,] 33   34   35   36   37   38   39   40  
[6,] 41   42   43   44   45   46   47   48  
[7,] 49   50   51   52   53   54   55   56  
[8,] 57   58   59   60   61   62   63   64

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1     9   17   25   33   41   49   57  
[2,] 2    10   18   26   34   42   50   58  
[3,] 3    11   19   27   35   43   51   59  
[4,] 4    12   20   28   36   44   52   60  
[5,] 5    13   21   29   37   45   53   61  
[6,] 6    14   22   30   38   46   54   62  
[7,] 7    15   23   31   39   47   55   63  
[8,] 8    16   24   32   40   48   56   64

Transpose the array

In [70]:
data<-t(data)
data

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  1    2    3    4    5    6    7    8  
[2,]  9   10   11   12   13   14   15   16  
[3,] 17   18   19   20   21   22   23   24  
[4,] 25   26   27   28   29   30   31   32  
[5,] 33   34   35   36   37   38   39   40  
[6,] 41   42   43   44   45   46   47   48  
[7,] 49   50   51   52   53   54   55   56  
[8,] 57   58   59   60   61   62   63   64

Print only the top 4 rows and columns

In [71]:
data[1:4,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  1    2    3    4    5    6    7    8  
[2,]  9   10   11   12   13   14   15   16  
[3,] 17   18   19   20   21   22   23   24  
[4,] 25   26   27   28   29   30   31   32

Make a 1D array out of your 2D array with the numbers 1 to 64 in order (note the column vs row issue, you may need transposes)

In [81]:
data <- as.vector(t(data))
data

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
[51] 51 52 53 54 55 56 57 58 59 60 61 62 63 64

Now take that 1D array you made from before and reshape it back to the original 2D array

In [86]:
t(array(data, c(8,8)))

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  1    2    3    4    5    6    7    8  
[2,]  9   10   11   12   13   14   15   16  
[3,] 17   18   19   20   21   22   23   24  
[4,] 25   26   27   28   29   30   31   32  
[5,] 33   34   35   36   37   38   39   40  
[6,] 41   42   43   44   45   46   47   48  
[7,] 49   50   51   52   53   54   55   56  
[8,] 57   58   59   60   61   62   63   64