# Basic Data Structures

# Lists (ordered collection of various objects)

### Instantiation

In [6]:
data = [1.7,"hello",4,"cat"]

### Accessing the first element

In [7]:
data[0]
#Outputs 1.7

1.7

### Updating an element

In [8]:
data[1] = 3.5
# data = [1.7,3.5,4,"cat"]
print(data)

[1.7, 3.5, 4, 'cat']


### Slicing a list (get the first 3 elements)

In [9]:
data[0:3]

[1.7, 3.5, 4]

### Finding the length of a list

We use the len() function.

In [10]:
len(data)
#Should output 4

4

### Accessing elements at the end of a list

In [11]:
last = data[-1]
print(last)
#Should output "cat"

cat


### Traversing through a list

This is useful if you don't need the index and if you're not changing anything.

In [12]:
for item in data:
    print(item)

1.7
3.5
4
cat


### Traversing a list by indices in the list

This technique is useful if you want to change items in the list.

In [13]:
for i in range(len(data)):
    print(data[i])

1.7
3.5
4
cat


### Contains

This method will return either True or False.

In [14]:
6 in data
#Returns False

False

In [15]:
1.7 in data
#Returns True

True

### Removing an element from a list by the item's position

In [16]:
del data[1]
#Deletes 3.5 from the list
print(data)

[1.7, 4, 'cat']


### Remove a single element from a list by the item's value

In [17]:
data.remove('cat')
#Removes 'cat' from the list
print(data)

[1.7, 4]


### Split string into a list

We want to break a string into a list based on a delimiter, which is usually a space " ". 

In [18]:
"my string is".split(" ")
# makes a list [“my”,”string”,”is”]


['my', 'string', 'is']

### Make string from a list or array of strings

In [19]:
" ".join( ["my","string","is"])

'my string is'

# Dictionary (collection of key-value pairs)

In Python, we call a collection of key-value pairs a dictionary, and a mix of key types is allowed.

### Instantiation

In [20]:
empty = {} 

song = {"A" : "do", "B": "re", "C" : "mi"}
#"A"->"do"
#"B"->"re"
#"C"->"mi"

### Finding the size of the dictionary

We also use the len() function to find the size of the dictionary.

In [21]:
len(song)
#Returns 3

3

### Looking up values by key in the dictionary

In [22]:
song['A']
#Returns 'do'

'do'

### Updating/Setting a value

In [23]:
song['A'] = 'fa'
song['A']

'fa'

### Get the list of keys

We use the keys() function. 

In [24]:
song.keys()
#Returns A,B,C

dict_keys(['A', 'B', 'C'])

### Get the list of values

We use the values() function.

In [25]:
song.values()
#Returns fa, re, mi

dict_values(['fa', 're', 'mi'])

### Determining if a key is present in the dictionary

In [26]:
'A' in song
#Returns True

True

### Removal

In [27]:
del song['A']
print(song)

{'B': 're', 'C': 'mi'}


### Traversal through the dictionary, iterating by key

In [28]:
for key in song:
    print(song[key])

re
mi


# 2D Arrays

In Python, we use the NumPy package, which is used for scientific computing with Python.

In [30]:
import numpy as np

### Instantiation

In [31]:
data = np.array([[1,2],[3,4]])

### Checking the array type

In [32]:
data.dtype

#Array of Integers

dtype('int64')

### Finding the dimensions of an array

In [33]:
data.shape

#2 rows and 2 colums

(2, 2)

### Find the number of rows or columns in an array

In [36]:
#Number of rows
print(data.shape[0])

#Number of columns
print(data.shape[1])

2
2


### Accessing the first value in an array

In [37]:
data[0,0]
#Returns 1

1

### Setting a value

In [38]:
data[0,0] = 5

### Copying an array

We copy an array by using NumPy's copy function. 

In [40]:
new_data = np.copy(data)
print(new_data)

[[5 2]
 [3 4]]


### Creating a 2x2 array of all zeroes

We create an array of all zeroes by using NumPy's zeros function. 

In [42]:
data = np.zeros((2,2))
print(data)

[[ 0.  0.]
 [ 0.  0.]]


### Creating a 2x2 array of all ones

We create an array of all ones by using NumPy's ones function.

In [44]:
data = np.ones((2,2))
print(data)

[[ 1.  1.]
 [ 1.  1.]]


### Slicing an array

In this example, we are trying to get the first column of the array.

In [74]:
data = np.array([[1,2],[3,4]])

print(data[0:2,0])
#OR
print()
print(data[:,0])

[1 3]

[1 3]


### Copy one array into a part of an array

In this example, we want to set the first column to zeroes.

In [75]:
print(data)

data[:,0] = [0,0]
print()
print(data)

[[1 2]
 [3 4]]

[[0 2]
 [0 4]]


### Transpose (flipping rows and columns)

We transpose an array bu using the transpose() function.

In [77]:
print(data.transpose())

[[0 0]
 [2 4]]


### Combining two arrays vertically

To combine two arrays vertically, we use NumPy's vstack function.

In [83]:
row1 = np.array([1,2,3])
row2 = np.array([4,5,6])
np.vstack((row1,row2))

array([[1, 2, 3],
       [4, 5, 6]])

### Reshaping a 1D array to a 2D array

In [87]:
np.arange(1,7).reshape(3,2)
#Shape arrays row first

array([[1, 2],
       [3, 4],
       [5, 6]])

### Reshape a 2D array into a 1D array

To reshape a 2D array into a 1D array, we want to use the flatten function, which returns a copy of the array collapsed into a 1D array. 

In [89]:
print(data.flatten())

[0 2 0 4]


# Helpful Links

<ol type = "1">
    <li>https://sebastianraschka.com/blog/2014/matrix_cheatsheet_table.html</li>
    <li> https://cheatsheets.quantecon.org/ </li>
    <li> http://hyperpolyglot.org/numerical-analysis </li>
    <li> http://mathesaurus.sourceforge.net/matlab-python-xref.pdf </li> 
</ol>